<Project>
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.2.0</Version>
    <Authors>Lunar</Authors>
    <Company>LunarSync</Company>
    <Product>LunarSync</Product>
    <Deterministic>true</Deterministic>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
</Project>
